### ISSUE TITLE
Mechanics checklist

### ISSUE THREAD

**Issue by Patrate** [FyzRDC/Rune#20]
- [x] Grimoire GUI
- [x] Learning spells
- [ ] Hand animation for parchment
- [ ] Hand animation for spells
- [x] Spell crafting interface
- [x] Loading spells
- [x] Charging spells
- [x] channeling spells
- [ ] Item cost
- [x] Block manipulation
- [ ] Other mana sources:
- [x] Wand
- [ ] Mana crystal
- [ ] Mana potion (from mana crystal)
- [x] Sockets
- [ ] Mana enchantment
- [ ] Necklace and ring
